unbind r
bind r source-file ~/.tmux.conf

# Options
set -g prefix C-s
set -g mouse on
set -g default-terminal "tmux-256color"
set -g history-limit 10000
set -g base-index 1
set -g renumber-windows on
set -g status-position top
set -g set-clipboard on
set -g focus-events on

# Key binds
bind-key - split-window -v
bind-key h split-window -h

# Display Popup's
bind-key g display-popup -w 80% -h 80% -E "lazygit"
# bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
# bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @plugin 'fcsonline/tmux-thumbs'
set -g @thumbs-command 'echo -n {} | wl-copy'
set -g @thumbs-position 'prefix'
set -g @thumbs-contrast 1
set -g @thumbs-reverse enabled
set -g @thumbs-regexp-1 '[A-Z][A-Z0-9]+-[0-9]+' # JIRA Tickets
set -g @thumbs-regexp-2 '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}' # Emails
set -g @thumbs-regexp-3 '(?:claude|cursor-agent) --resume [a-fA-F0-9]{8}-(?:[a-fA-F0-9]{4}-){3}[a-fA-F0-9]{12}' # Agents Resume

set -g @plugin 'martiis/tmux-sessionx'
set -g @sessionx-bind 'o'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'
# set -g @sessionx-x-path '/home/user/Work'
# set -g @sessionx-custom-paths 'home/user/Work'
set -g @sessionx-custom-paths-subdirectories 'true'
set -g @sessionx-custom-paths-depth '2'
set -g @sessionx-custom-paths-display 'relative'
set -g @sessionx-window-height '75%'
set -g @sessionx-window-width '75%'

set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "slanted"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag,(),}"
set -g @catppuccin_memory_text "#(free | awk '/Mem:/ {pct=$3/$2*100; filled=int(pct/10); printf \"[\"; for (i=0;i<10;i++) printf \"%s\", (i<filled ? \"=\" : \"-\"); printf \"] %.0f%%\", pct}')"
set -g @catppuccin_status_memory "#[fg=#{@thm_mauve}]#{@catppuccin_status_left_separator}#[fg=#{@thm_crust},bg=#{@thm_mauve}]󰍛 #[fg=#{@thm_fg},bg=#{@catppuccin_status_module_text_bg}]#{E:@catppuccin_memory_text}#[fg=#{@catppuccin_status_module_text_bg}]#{@catppuccin_status_right_separator}"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_memory}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Pane borders
set -g pane-border-lines double
set -g pane-active-border-style "fg=#cba6f7"
set -g pane-border-style "fg=#585b70"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
